---

- name: Update package cache
  dnf:
    update_cache: yes
  run_once: yes
  tags:
    - update_cache

- name: Place convenience scripts
  include: convenience-scripts.yml
  tags:
    - convenience
    - never
