- name: install pre-requisites
  dnf:
    name: containerd.io
    state: latest
    update_cache: true


- name: install the latest version of Docker CE
  dnf:
    name: docker-ce
    state: latest    
