---
- name: Template Nginx config file
  template:
    src: nginx.conf.j2
    dest: /opt/nginx.conf
    mode: '0644'

- name: install the EPEL rpm from repository
  dnf:
    name: epel-release
    state: present

- name: Install Certbot
  dnf:
    name:
      - certbot
      - python3-certbot-nginx
    state: latest

- name: Generate certificate for Nginx
  command: /usr/bin/certbot --nginx
