---

- name: Initialize a new swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ swarm_iface | default('eth0') }}:2377" 

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token

- name: Set manager join token as a fact on all hosts
  set_fact:
    manager_join_token: "{{ manager_token.stdout }}"
    delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- debug:
    var: manager_join_token
    verbosity: 2

- name: Get the Worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token

- name: Set worker join token as a fact on all hosts
  set_fact:
    worker_join_token: "{{ worker_token.stdout }}"
    delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- debug:
    var: worker_join_token
    verbosity: 2
