- name: Install pre-requisites
  dnf:
    name:
      - python3
    state: latest

- name: Uninstall docker-py
  pip:
    name: docker-py
    state: absent

- name: Install Docker Python SDK
  pip:
    name: docker
