---

- name: Create directories
  file:
    path:
      - /opt/nginx      
    state: directory
    mode: '0755'

- name: Template Nginx config file
  template:
    src: nginx.conf.j2
    dest: /opt/nginx/nginx.conf
    mode: '0644'

- name: install EPEL
  dnf:
    name: epel-release
    state: present

- name: Install Certbot
  dnf:
    name:
      - certbot
      - python3-certbot-nginx
    state: latest

- name: Call certificate signing tasks
  include: generate-certs.yml
