---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /opt/nginx
    - /opt/nginx/sites-available

- name: Template Nginx config file
  template:
    src: nginx/nginx.conf.j2
    dest: /opt/nginx/nginx.conf
    mode: '0644'

- name: Call certificate signing tasks
  include: generate-certs.yml

# - name: Load Certificate Key Pair
#   include: load-key-pair.yml
