---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/ssl
    - /etc/ssl/crt
    - /etc/ssl/csr
    - /etc/ssl/private

- name: Generate a new OpenSSL private key
  openssl_privatekey:
    path: /etc/ssl/private/local.poodle.pem
    force: yes

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path: /etc/ssl/csr/local.poodle.csr
    privatekey_path: /etc/ssl/private/local.poodle.pem
    country_name: ZA
    organization_name: FarrOut
    email_address: farr.gs@gmail.com
    common_name: Poodle

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/local.poodle.crt
    privatekey_path: /etc/ssl/private/local.poodle.pem
    csr_path: /etc/ssl/csr/local.poodle.csr
    provider: selfsigned
