---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /opt/nginx
    - /opt/nginx/sites-available

- name: Template Nginx site file
  template:
    src: nginx/sites-available.j2
    dest: /opt/nginx/sites-available/default
    mode: '0644'
