---
- name: Disabling swarm
  become: yes
  command: docker swarm leave -f
  ignore_errors: yes
  tags:
    - docker
    - swarm
    - manager
    - reset

- name: Initialize Swarm
  include_tasks: init-swarm.yml
  run_once: true
  tags:
    - docker
    - swarm
    - init
    - reset

- name: Deploy service stack
  include_tasks: service-stack.yml
  run_once: true
