---
- name: Install common packages
  hosts: swarm
  roles:
   - docker
   - docker-swarm

# Deploy a customized Moodle stack to a Docker Swarm.

- name:           Deploy the swarm managers
  hosts:          managers
  become:         yes
  become_method:  sudo

  roles:
   - docker-swarm-manager

- name:           Deploy the swarm workers
  hosts:          workers
  become:         yes
  become_method:  sudo

  roles:
   - docker-swarm-worker
