---
- name: Install common packages
  hosts: all
  become:         yes
  become_method:  sudo
  roles:
   - common
   - docker

# Deploy a customized stack to a Docker Swarm.
- name:           Deploy 'The Boss'
  hosts:          boss
  become:         yes
  become_method:  sudo

  roles:
   - docker-swarm

- name:           Deploy additional swarm managers
  hosts:          managers
  become:         yes
  become_method:  sudo

  roles:
   - docker-swarm-manager

- name:           Deploy the swarm workers
  hosts:          workers
  become:         yes
  become_method:  sudo

  roles:
   - docker-swarm-worker
