---
# Deploy a customized Moodle stack to a clustered layout.

- name:           Deploy the swarm managers
  hosts:          managers
  become:         yes
  become_method:  sudo

  roles:
  - docker
  - docker-swarm-manager
