# vars file for dockermanager
tokennode: "{{ hostvars.manager.bootstrap_first_node.stdout.split('\n')[5].split(' ')[5] }}"
hostmanager: "{{ hostvars.manager.bootstrap_first_node.stdout.split('\n')[6] }}"
